# DESCRIPTION: atome application
mysql:
  image: 'dekka/mysql:latest'

  volumes:
    - ${BPP_MYSQL_VOLUME_NAME}:/var/lib/mysql
    - ${BPP_APPLICATION_VOLUME_NAME}:/opt/atome

  ports:
    - 3306:3306/tcp